
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euwulgurffyxhazhirqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1d3VsZ3VyZmZ5eGhhemhpcnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Mjc5ODcsImV4cCI6MjA1OTQwMzk4N30.Nz8VanS1hR1YrOSqen0wFqVeGPGsIEhR3jZt_b0VhVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
